// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ykIGMM2tzV4ZQCSF4isquc--CkI5aFA',
    appId: '1:218445850862:web:44df11bc2e96486f53ebff',
    messagingSenderId: '218445850862',
    projectId: 'fir-d45d1',
    authDomain: 'fir-d45d1.firebaseapp.com',
    storageBucket: 'fir-d45d1.firebasestorage.app',
    measurementId: 'G-JZQ5PJX8VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRNFGr2oJxxn46oFe-WPDCiU7AO_mhjbg',
    appId: '1:218445850862:android:b241575efa847b4e53ebff',
    messagingSenderId: '218445850862',
    projectId: 'fir-d45d1',
    storageBucket: 'fir-d45d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1O7QPJQQKLIXNYamugAKdvbINMh20sA4',
    appId: '1:218445850862:ios:a4fc53fd355ba0cb53ebff',
    messagingSenderId: '218445850862',
    projectId: 'fir-d45d1',
    storageBucket: 'fir-d45d1.firebasestorage.app',
    iosBundleId: 'com.example.cambridgeUniversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1O7QPJQQKLIXNYamugAKdvbINMh20sA4',
    appId: '1:218445850862:ios:a4fc53fd355ba0cb53ebff',
    messagingSenderId: '218445850862',
    projectId: 'fir-d45d1',
    storageBucket: 'fir-d45d1.firebasestorage.app',
    iosBundleId: 'com.example.cambridgeUniversity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEdky8-mgAwGnHWMBn5V7YxaLCmOIqIPI',
    appId: '1:218445850862:web:c5cd68c1e17e234553ebff',
    messagingSenderId: '218445850862',
    projectId: 'fir-d45d1',
    authDomain: 'fir-d45d1.firebaseapp.com',
    storageBucket: 'fir-d45d1.firebasestorage.app',
    measurementId: 'G-75F1PBYZQQ',
  );

}